Add concept of anchor sources
decentralized-identity/sidetree pull request #1035
Opened 2021-02-12 16:15 UTC by troyronda

See #1034 for background.

2021-02-12 16:16 UTC, OR13 submitted a review, later dismissed

2021-02-14 04:11 UTC, csuwildcat requested changes
We should probably specify that the properties are MAY implement as well as MAY be present, because in implementations that don't implement the props, they will likely (should?) throw on the presence of unrecognized properties.

2021-02-14 16:31 UTC, troyronda commented
@csuwildcat Sure - will push an update.

2021-02-14 19:39 UTC, troyronda commented
@csuwildcat Added clarifying language that the property is implementation-defined and MAY be included if the implementation defines it.

2021-02-15 14:29 UTC, csuwildcat approved these changes

2021-02-15 14:29 UTC, merged